[package]
name = "neo"
version = "1.3.1"
edition = "2021"
build = "build.rs"

[package.metadata.winres]
FileDescription = "E621 / E926 Image Downloader"

[dependencies]
color-eyre = { version = "0.6.3", default-features = false }
loading = "*"
once_cell = "1.19.0"
reqwest = { version = "0.12.4", features = ["blocking"] }
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
serde_yaml = "0.9.34"

[build-dependencies]
# winres project
winres = "0.1.12"

[patch.crates-io]
winres = { git = "https://github.com/sandydoo/winres", branch = "bugfix/fix-linking" }
